databases:
  - name: msmqueries
    plan: free
    databaseName: MSM-QUERIES
    user: MSM-QUERIES

services:
  - type: web
    name: msmqueries
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msmqueries
          property: connectionString
      - key: 473a488f44703f7556565a8fdd7f4d06
        sync: false
