databases:
  - name: msmqueries
    plan: free
    databaseName: msmqueries
    user: msmqueries

services:
  - type: web
    name: msmqueries
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msmqueries
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
